function CSC02120230130corrected = import_corrected_USevents_file(filename, dataLines)
%IMPORTFILE Import data from a text file
%  CSC02120230130CORRECTED = import_corrected_USevents_file(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  CSC02120230130CORRECTED = import_corrected_USevents_file(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  CSC02120230130corrected = import_corrected_USevents_file("\\ktdata\snlkt\specialk_cs\SLEAP\facial_analysis\lk_processed_v2\event_csv_v1\CSC021_20230130_corrected.csv", [3, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 24-Apr-2024 14:29:49

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [3, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 9);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Subject", "Session", "Stimulus_type", "PrePost", "Orig_US_FrameNum", "TRUE", "multiplier", "Estimated", "difference"];
opts.VariableTypes = ["string", "double", "string", "string", "double", "double", "string", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Subject", "Stimulus_type", "PrePost", "multiplier"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Subject", "Stimulus_type", "PrePost", "multiplier"], "EmptyFieldRule", "auto");

% Import the data
CSC02120230130corrected = readtable(filename, opts);

% clean up table
CSC02120230130corrected=CSC02120230130corrected(~isnan(CSC02120230130corrected.TRUE),:); %remove nan entries from TRUE
CSC02120230130corrected.multiplier = []; % don't need this
CSC02120230130corrected.difference = []; % don't need this


end